name: 🐛 Reporte de Error
description: Plantilla para reportar bugs y errores en Iravic Designs
title: "[BUG] "
labels: ["bug", "needs-investigation"]
assignees:
  - CarlosMaita
body:
  - type: markdown
    attributes:
      value: |
        # 🐛 Reporte de Error
        
        Gracias por ayudar a mejorar Iravic Designs reportando este error. 
        Por favor, proporciona la mayor información posible para ayudarnos a reproducir y solucionar el problema.

  - type: input
    id: bug-summary
    attributes:
      label: 📝 Resumen del Error
      description: Describe brevemente el error encontrado
      placeholder: "Ej: Error al aplicar descuento en el carrito de compras"
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: 📋 Descripción Detallada
      description: Describe detalladamente qué está sucediendo
      placeholder: |
        Describe el error de manera clara y detallada:
        - ¿Qué esperabas que sucediera?
        - ¿Qué está sucediendo en su lugar?
        - ¿Cuándo comenzó a ocurrir este problema?
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 🔄 Pasos para Reproducir
      description: Lista los pasos exactos para reproducir el error
      placeholder: |
        1. Ir a...
        2. Hacer clic en...
        3. Escribir...
        4. Ver error
      value: |
        1. 
        2. 
        3. 
        4. 
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ Comportamiento Esperado
      description: Describe qué debería suceder normalmente
      placeholder: "Describe el comportamiento correcto que esperabas..."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: ❌ Comportamiento Actual
      description: Describe qué está sucediendo en realidad
      placeholder: "Describe qué está sucediendo en lugar del comportamiento esperado..."
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: 🚨 Severidad del Error
      description: ¿Qué tan crítico es este error?
      options:
        - 🔴 Crítico - El sistema no funciona / Pérdida de datos
        - 🟠 Alto - Funcionalidad principal afectada
        - 🟡 Medio - Funcionalidad secundaria afectada
        - 🟢 Bajo - Problema cosmético / Menor
    validations:
      required: true

  - type: dropdown
    id: frequency
    attributes:
      label: 📊 Frecuencia
      description: ¿Con qué frecuencia ocurre este error?
      options:
        - 🔴 Siempre - Ocurre cada vez
        - 🟠 Frecuentemente - Ocurre la mayoría de las veces
        - 🟡 A veces - Ocurre ocasionalmente
        - 🟢 Raramente - Ocurre muy pocas veces
        - ❓ No estoy seguro - Difícil de determinar
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 🖥️ Información del Entorno
      description: Proporciona información sobre tu entorno de ejecución
      placeholder: |
        **Sistema Operativo:** (ej: Windows 10, macOS 12, Ubuntu 20.04)
        **Navegador:** (ej: Chrome 96, Firefox 95, Safari 15)
        **Versión de PHP:** (ej: 8.1)
        **Versión de Laravel:** (ej: 9.x)
        **Versión de Node.js:** (ej: 16.x)
        **Base de Datos:** (ej: MySQL 8.0, SQLite)
        **Entorno:** (ej: local, desarrollo, producción)
      value: |
        **Sistema Operativo:** 
        **Navegador:** 
        **Versión de PHP:** 
        **Versión de Laravel:** 
        **Versión de Node.js:** 
        **Base de Datos:** 
        **Entorno:** 
    validations:
      required: true

  - type: textarea
    id: error-logs
    attributes:
      label: 📝 Logs de Error
      description: Copia y pega cualquier mensaje de error o log relevante
      placeholder: |
        Incluye logs de:
        - Laravel logs (storage/logs/laravel.log)
        - Console del navegador (F12 > Console)
        - Logs del servidor web
        - Cualquier otro mensaje de error relevante
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: 📸 Capturas de Pantalla
      description: Adjunta capturas de pantalla que muestren el error
      placeholder: |
        Arrastra y suelta las imágenes aquí o incluye enlaces:
        - Captura del error en pantalla
        - Captura de los logs de error
        - Cualquier otra imagen relevante

  - type: dropdown
    id: module-affected
    attributes:
      label: 🏗️ Módulo Afectado
      description: ¿Qué módulo del sistema está experimentando el error?
      options:
        - 🛍️ E-commerce / Catálogo de Productos
        - 👥 Gestión de Clientes
        - 📦 Control de Inventario
        - 💳 Pagos y Facturación
        - 📊 Reportes y Analytics
        - 👨‍💼 Panel de Administración
        - 🔐 Autenticación y Roles
        - 🚚 Logística y Envíos
        - 🎨 Frontend / UI/UX
        - 🔌 API / Integraciones
        - 📱 Aplicación Móvil
        - 🔧 Configuración del Sistema
        - ❓ No estoy seguro
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Contexto Adicional
      description: Cualquier información adicional que pueda ser útil
      placeholder: |
        - ¿Has realizado cambios recientes en el código?
        - ¿El error comenzó después de una actualización?
        - ¿Has intentado alguna solución?
        - ¿Hay algún patrón específico que notes?
        - ¿Afecta a todos los usuarios o solo a algunos?

  - type: checkboxes
    id: troubleshooting
    attributes:
      label: 🔧 Pasos de Resolución Intentados
      description: Marca los pasos que ya has intentado para resolver el problema
      options:
        - label: Limpieza de caché del navegador
          required: false
        - label: Reinicio del servidor web
          required: false
        - label: Limpieza de caché de Laravel (php artisan cache:clear)
          required: false
        - label: Revisión de logs de error
          required: false
        - label: Actualización de dependencias
          required: false
        - label: Verificación de configuración de base de datos
          required: false
        - label: Prueba en navegador diferente
          required: false
        - label: Revisión de permisos de archivos
          required: false

  - type: checkboxes
    id: confirmation
    attributes:
      label: ✔️ Confirmación
      description: Confirma la información proporcionada
      options:
        - label: He proporcionado pasos claros para reproducir el error
          required: true
        - label: He incluido información del entorno
          required: true
        - label: He verificado que no existe un issue similar
          required: true
        - label: He incluido logs de error cuando están disponibles
          required: true

  - type: markdown
    attributes:
      value: |
        ---
        
        ## 📚 Recursos de Ayuda
        
        - [Documentación de Resolución de Problemas](https://github.com/CarlosMaita/iravic-designs#readme)
        - [Issues Existentes](https://github.com/CarlosMaita/iravic-designs/issues)
        - [Estándares de Codificación](https://github.com/CarlosMaita/iravic-designs/blob/main/CODING_STANDARDS.md)
        
        **¡Gracias por ayudar a mejorar Iravic Designs! 🛠️**